### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by yurrriq**
### deps
- lutil: 0.8.1 -> 0.9.0

### plugins
- lfe-compile: 0.4.0 -> 0.5.0

### lodox: 0.12.4 -> 0.15.1
  - lfe: 1.0.2 -> 1.1.1
  - clj: 0.4.1 -> 0.5.0
  - levaindoc: 0.5.0 -> 0.6.1

### dev
  - lfe: 1.0.2 -> 1.1.1
  - lfe-version: 0.3.2 -> 0.4.0
  - lee-clean: 0.2.0 -> 0.3.0

### TODO
- [x] Bump exemplar version (4f14ab3)
- [ ] Merge this
- [ ] Tag exemplar 0.4.2
- [ ] Update lodox
  - [x] Ditch obviated overrides (https://github.com/lfe-rebar3/lodox/commit/d09f99151199975c5035ed5bfa121e63cce69efd)
  - [x] Bump exemplar dep ([lfe-rebar3/lodox@d09f991/rebar.config:9-10](https://github.com/lfe-rebar3/lodox/blob/d09f99151199975c5035ed5bfa121e63cce69efd/rebar.config#L9-L10))
  - [x] Bump version (https://github.com/lfe-rebar3/lodox/commit/491246a20d8da5676d1478af21d4a1724240727f)
  - [ ] Tag 0.16.2
- [ ] Bump lodox tag to 0.16.2 in exemplar
- [ ] Update docs

### CODE REVIEW

**Comment by yurrriq** [comment]
Note that despite the unfinished todo list above, this is ready to merge.

**Comment by yurrriq** [comment]
Maybe hold off on this till the next LFE release. I'm dogfooding clj.lfe in lodox (and Pynchon) now and it'd be better to do a proper release of exemplar on LFE-1.2 or whatever the update those projects.

**Comment by oubiwann** [comment]
I'm going to go ahead and merge this, but please note that many of these changes will soon be superseded; don't take offense: it's happening to all the LFE projects I maintain. (You'll still get credit for this commits and file changes.)

**Comment by yurrriq** [comment]
No worries. I think this PR is stale it this point. Sorry again about the other day.

**Pull request merged**
